2025-04-29 14:05:50,995 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-04-29 14:05:53,129 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-04-29 14:05:53,316 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-04-29 14:05:53,499 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-04-29 14:06:04,593 - httpx - INFO - HTTP Request: POST https://api.x.ai/v1/chat/completions "HTTP/1.1 200 OK"
2025-04-29 14:06:05,679 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-04-29 14:06:05,680 - rag - INFO - Retrieved document: source=https://www.maxwellgeosystems.com/manuals/demo-manual/manual-web-content-highlight.php?manual_id=55, videos=[{'url': 'https://www.youtube.com/watch?v=cmMoBIWyQt8', 'title': 'How To: Configure A Project in MissionOS'}, {'url': 'https://www.youtube.com/watch?v=gcZKN_JiDYk', 'title': 'Shorts 1 - Introduction to Interface'}, {'url': 'https://www.youtube.com/watch?v=hvWbD7Z2LrM', 'title': 'Shorts 2 - Update Project Configuration'}]
2025-04-29 14:06:05,680 - rag - INFO - Retrieved document: source=https://www.maxwellgeosystems.com/manuals/demo-manual/manual-web-content-highlight.php?manual_id=55, videos=[{'url': 'https://www.youtube.com/watch?v=cmMoBIWyQt8', 'title': 'How To: Configure A Project in MissionOS'}, {'url': 'https://www.youtube.com/watch?v=gcZKN_JiDYk', 'title': 'Shorts 1 - Introduction to Interface'}, {'url': 'https://www.youtube.com/watch?v=hvWbD7Z2LrM', 'title': 'Shorts 2 - Update Project Configuration'}]
2025-04-29 14:06:05,680 - rag - INFO - Retrieved document: source=https://www.maxwellgeosystems.com/manuals/demo-manual/manual-web-content-highlight.php?manual_id=55, videos=[{'url': 'https://www.youtube.com/watch?v=cmMoBIWyQt8', 'title': 'How To: Configure A Project in MissionOS'}, {'url': 'https://www.youtube.com/watch?v=gcZKN_JiDYk', 'title': 'Shorts 1 - Introduction to Interface'}, {'url': 'https://www.youtube.com/watch?v=hvWbD7Z2LrM', 'title': 'Shorts 2 - Update Project Configuration'}]
2025-04-29 14:06:05,680 - rag - INFO - Retrieved document: source=https://www.maxwellgeosystems.com/manuals/demo-manual/manual-web-content-highlight.php?manual_id=47, videos=[{'url': 'https://www.youtube.com/watch?v=H_cTgnXqkFQ', 'title': 'How To: Create Object Type Permissions'}, {'url': 'https://www.youtube.com/watch?v=POkNZPtGrQU', 'title': 'Shorts 1 - How to access Permission Tags'}, {'url': 'https://www.youtube.com/watch?v=Ffliy0elSdM', 'title': 'Shorts 2 - How to edit a Permission Tag'}]
2025-04-29 14:06:06,490 - rag - INFO - retrieve: Returning videos: [{'url': 'https://www.youtube.com/watch?v=POkNZPtGrQU', 'title': 'Shorts 1 - How to access Permission Tags'}, {'url': 'https://www.youtube.com/watch?v=H_cTgnXqkFQ', 'title': 'How To: Create Object Type Permissions'}, {'url': 'https://www.youtube.com/watch?v=Ffliy0elSdM', 'title': 'Shorts 2 - How to edit a Permission Tag'}, {'url': 'https://www.youtube.com/watch?v=gcZKN_JiDYk', 'title': 'Shorts 1 - Introduction to Interface'}, {'url': 'https://www.youtube.com/watch?v=hvWbD7Z2LrM', 'title': 'Shorts 2 - Update Project Configuration'}, {'url': 'https://www.youtube.com/watch?v=cmMoBIWyQt8', 'title': 'How To: Configure A Project in MissionOS'}]
2025-04-29 14:06:06,492 - rag - INFO - Extracted query from st.session_state.messages: How do I set-up a project?
2025-04-29 14:06:06,493 - rag - INFO - Retrieved chunk 1: Qdrant Point ID=3fcb3464-d7f4-48e6-a8d1-15a313384099, URL=https://www.maxwellgeosystems.com/manuals/demo-manual/manual-web-content-highlight.php?manual_id=55, Videos=[{'url': 'https://www.youtube.com/watch?v=POkNZPtGrQU', 'title': 'Shorts 1 - How to access Permission Tags'}, {'url': 'https://www.youtube.com/watch?v=H_cTgnXqkFQ', 'title': 'How To: Create Object Type Permissions'}, {'url': 'https://www.youtube.com/watch?v=Ffliy0elSdM', 'title': 'Shorts 2 - How to edit a Permission Tag'}, {'url': 'https://www.youtube.com/watch?v=gcZKN_JiDYk', 'title': 'Shorts 1 - Introduction to Interface'}, {'url': 'https://www.youtube.com/watch?v=hvWbD7Z2LrM', 'title': 'Shorts 2 - Update Project Configuration'}, {'url': 'https://www.youtube.com/watch?v=cmMoBIWyQt8', 'title': 'How To: Configure A Project in MissionOS'}], Text preview=Version:MissionOS_2.0 How do you configure a new project? If you want to configure a new project in MissionOS, first log into the application using the portal URL, Username and Password. To configure your project, click open the Data Manager . ![image:db://images/12680](db://images/12680) Figure 1: Click open Data Manager In the Data Manager page, you can access Admin > Setup > Project from the navigation pane, where you can set up project details...
2025-04-29 14:06:06,493 - rag - INFO - Retrieved chunk 2: Qdrant Point ID=2eb443a6-9221-463e-aa06-6f21e13bc0c4, URL=https://www.maxwellgeosystems.com/manuals/demo-manual/manual-web-content-highlight.php?manual_id=55, Videos=[{'url': 'https://www.youtube.com/watch?v=POkNZPtGrQU', 'title': 'Shorts 1 - How to access Permission Tags'}, {'url': 'https://www.youtube.com/watch?v=H_cTgnXqkFQ', 'title': 'How To: Create Object Type Permissions'}, {'url': 'https://www.youtube.com/watch?v=Ffliy0elSdM', 'title': 'Shorts 2 - How to edit a Permission Tag'}, {'url': 'https://www.youtube.com/watch?v=gcZKN_JiDYk', 'title': 'Shorts 1 - Introduction to Interface'}, {'url': 'https://www.youtube.com/watch?v=hvWbD7Z2LrM', 'title': 'Shorts 2 - Update Project Configuration'}, {'url': 'https://www.youtube.com/watch?v=cmMoBIWyQt8', 'title': 'How To: Configure A Project in MissionOS'}], Text preview=? If you want to configure a new project in MissionOS, first log into the application using the portal URL, Username and Password...
2025-04-29 14:06:06,493 - rag - INFO - Retrieved chunk 3: Qdrant Point ID=a074cd6d-226a-4e39-b450-6352ec887143, URL=https://www.maxwellgeosystems.com/manuals/demo-manual/manual-web-content-highlight.php?manual_id=55, Videos=[{'url': 'https://www.youtube.com/watch?v=POkNZPtGrQU', 'title': 'Shorts 1 - How to access Permission Tags'}, {'url': 'https://www.youtube.com/watch?v=H_cTgnXqkFQ', 'title': 'How To: Create Object Type Permissions'}, {'url': 'https://www.youtube.com/watch?v=Ffliy0elSdM', 'title': 'Shorts 2 - How to edit a Permission Tag'}, {'url': 'https://www.youtube.com/watch?v=gcZKN_JiDYk', 'title': 'Shorts 1 - Introduction to Interface'}, {'url': 'https://www.youtube.com/watch?v=hvWbD7Z2LrM', 'title': 'Shorts 2 - Update Project Configuration'}, {'url': 'https://www.youtube.com/watch?v=cmMoBIWyQt8', 'title': 'How To: Configure A Project in MissionOS'}], Text preview=Version:MissionOS_2.0 How do you configure a new project...
2025-04-29 14:06:06,493 - rag - INFO - Retrieved chunk 4: Qdrant Point ID=66c12369-f0cf-4219-a9e0-a806b0801e07, URL=https://www.maxwellgeosystems.com/manuals/demo-manual/manual-web-content-highlight.php?manual_id=47, Videos=[{'url': 'https://www.youtube.com/watch?v=POkNZPtGrQU', 'title': 'Shorts 1 - How to access Permission Tags'}, {'url': 'https://www.youtube.com/watch?v=H_cTgnXqkFQ', 'title': 'How To: Create Object Type Permissions'}, {'url': 'https://www.youtube.com/watch?v=Ffliy0elSdM', 'title': 'Shorts 2 - How to edit a Permission Tag'}, {'url': 'https://www.youtube.com/watch?v=gcZKN_JiDYk', 'title': 'Shorts 1 - Introduction to Interface'}, {'url': 'https://www.youtube.com/watch?v=hvWbD7Z2LrM', 'title': 'Shorts 2 - Update Project Configuration'}, {'url': 'https://www.youtube.com/watch?v=cmMoBIWyQt8', 'title': 'How To: Configure A Project in MissionOS'}], Text preview=Version:MissionOS_2.0 Admin > Setup > Permissions Once you configure the new project, and hierarchy, the next step is to setup Permissions...
2025-04-29 14:06:06,494 - rag - INFO - Successfully wrote 4 chunks to retrieved_chunks.csv
2025-04-29 14:06:14,895 - httpx - INFO - HTTP Request: POST https://api.x.ai/v1/chat/completions "HTTP/1.1 200 OK"
2025-04-29 14:06:15,017 - ui - INFO - Rendering videos: [{'url': 'https://www.youtube.com/watch?v=POkNZPtGrQU', 'title': 'Shorts 1 - How to access Permission Tags'}, {'url': 'https://www.youtube.com/watch?v=H_cTgnXqkFQ', 'title': 'How To: Create Object Type Permissions'}, {'url': 'https://www.youtube.com/watch?v=Ffliy0elSdM', 'title': 'Shorts 2 - How to edit a Permission Tag'}, {'url': 'https://www.youtube.com/watch?v=gcZKN_JiDYk', 'title': 'Shorts 1 - Introduction to Interface'}, {'url': 'https://www.youtube.com/watch?v=hvWbD7Z2LrM', 'title': 'Shorts 2 - Update Project Configuration'}, {'url': 'https://www.youtube.com/watch?v=cmMoBIWyQt8', 'title': 'How To: Configure A Project in MissionOS'}]
2025-04-29 14:12:09,956 - ui - INFO - Rendering videos: [{'url': 'https://www.youtube.com/watch?v=POkNZPtGrQU', 'title': 'Shorts 1 - How to access Permission Tags'}, {'url': 'https://www.youtube.com/watch?v=H_cTgnXqkFQ', 'title': 'How To: Create Object Type Permissions'}, {'url': 'https://www.youtube.com/watch?v=Ffliy0elSdM', 'title': 'Shorts 2 - How to edit a Permission Tag'}, {'url': 'https://www.youtube.com/watch?v=gcZKN_JiDYk', 'title': 'Shorts 1 - Introduction to Interface'}, {'url': 'https://www.youtube.com/watch?v=hvWbD7Z2LrM', 'title': 'Shorts 2 - Update Project Configuration'}, {'url': 'https://www.youtube.com/watch?v=cmMoBIWyQt8', 'title': 'How To: Configure A Project in MissionOS'}]
2025-04-29 14:23:33,577 - database - INFO - Processing 153 documents
2025-04-29 14:23:33,814 - database - INFO - Created 550 chunks/documents
2025-04-29 14:23:35,319 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-04-29 14:23:39,990 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points?wait=true "HTTP/1.1 200 OK"
2025-04-29 14:23:43,361 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points?wait=true "HTTP/1.1 200 OK"
2025-04-29 14:23:45,499 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points?wait=true "HTTP/1.1 200 OK"
2025-04-29 14:23:46,657 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points?wait=true "HTTP/1.1 200 OK"
2025-04-29 14:23:48,539 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points?wait=true "HTTP/1.1 200 OK"
2025-04-29 14:23:49,803 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points?wait=true "HTTP/1.1 200 OK"
2025-04-29 14:23:50,736 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points?wait=true "HTTP/1.1 200 OK"
2025-04-29 14:23:51,555 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points?wait=true "HTTP/1.1 200 OK"
2025-04-29 14:23:52,426 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points?wait=true "HTTP/1.1 200 OK"
2025-04-29 14:23:52,547 - ui - INFO - Rendering videos: [{'url': 'https://www.youtube.com/watch?v=POkNZPtGrQU', 'title': 'Shorts 1 - How to access Permission Tags'}, {'url': 'https://www.youtube.com/watch?v=H_cTgnXqkFQ', 'title': 'How To: Create Object Type Permissions'}, {'url': 'https://www.youtube.com/watch?v=Ffliy0elSdM', 'title': 'Shorts 2 - How to edit a Permission Tag'}, {'url': 'https://www.youtube.com/watch?v=gcZKN_JiDYk', 'title': 'Shorts 1 - Introduction to Interface'}, {'url': 'https://www.youtube.com/watch?v=hvWbD7Z2LrM', 'title': 'Shorts 2 - Update Project Configuration'}, {'url': 'https://www.youtube.com/watch?v=cmMoBIWyQt8', 'title': 'How To: Configure A Project in MissionOS'}]
2025-04-29 14:40:04,882 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-04-29 14:40:05,370 - ui - INFO - Rendering videos: [{'url': 'https://www.youtube.com/watch?v=POkNZPtGrQU', 'title': 'Shorts 1 - How to access Permission Tags'}, {'url': 'https://www.youtube.com/watch?v=H_cTgnXqkFQ', 'title': 'How To: Create Object Type Permissions'}, {'url': 'https://www.youtube.com/watch?v=Ffliy0elSdM', 'title': 'Shorts 2 - How to edit a Permission Tag'}, {'url': 'https://www.youtube.com/watch?v=gcZKN_JiDYk', 'title': 'Shorts 1 - Introduction to Interface'}, {'url': 'https://www.youtube.com/watch?v=hvWbD7Z2LrM', 'title': 'Shorts 2 - Update Project Configuration'}, {'url': 'https://www.youtube.com/watch?v=cmMoBIWyQt8', 'title': 'How To: Configure A Project in MissionOS'}]
2025-04-29 14:42:45,484 - database - INFO - Processing 153 documents
2025-04-29 14:42:45,707 - database - INFO - Created 550 chunks/documents
2025-04-29 14:42:47,299 - httpx - INFO - HTTP Request: DELETE https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-04-29 14:42:47,962 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-04-29 14:45:28,705 - database - INFO - Processing 153 documents
2025-04-29 14:45:28,922 - database - INFO - Created 545 chunks/documents
2025-04-29 14:45:32,601 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points?wait=true "HTTP/1.1 200 OK"
2025-04-29 14:45:34,960 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points?wait=true "HTTP/1.1 200 OK"
2025-04-29 14:45:36,181 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points?wait=true "HTTP/1.1 200 OK"
2025-04-29 14:45:37,655 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points?wait=true "HTTP/1.1 200 OK"
2025-04-29 14:45:39,594 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points?wait=true "HTTP/1.1 200 OK"
2025-04-29 14:45:40,748 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points?wait=true "HTTP/1.1 200 OK"
2025-04-29 14:45:41,897 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points?wait=true "HTTP/1.1 200 OK"
2025-04-29 14:45:42,842 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points?wait=true "HTTP/1.1 200 OK"
2025-04-29 14:45:44,096 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points?wait=true "HTTP/1.1 200 OK"
2025-04-29 14:45:44,662 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-04-29 14:45:49,957 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points?wait=true "HTTP/1.1 200 OK"
2025-04-29 14:45:53,588 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points?wait=true "HTTP/1.1 200 OK"
2025-04-29 14:45:56,295 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points?wait=true "HTTP/1.1 200 OK"
2025-04-29 14:45:57,118 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points?wait=true "HTTP/1.1 200 OK"
2025-04-29 14:45:59,343 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points?wait=true "HTTP/1.1 200 OK"
2025-04-29 14:46:00,136 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points?wait=true "HTTP/1.1 200 OK"
2025-04-29 14:46:01,382 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points?wait=true "HTTP/1.1 200 OK"
2025-04-29 14:46:02,226 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points?wait=true "HTTP/1.1 200 OK"
2025-04-29 14:46:03,029 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points?wait=true "HTTP/1.1 200 OK"
2025-04-29 14:46:03,167 - ui - INFO - Rendering videos: [{'url': 'https://www.youtube.com/watch?v=POkNZPtGrQU', 'title': 'Shorts 1 - How to access Permission Tags'}, {'url': 'https://www.youtube.com/watch?v=H_cTgnXqkFQ', 'title': 'How To: Create Object Type Permissions'}, {'url': 'https://www.youtube.com/watch?v=Ffliy0elSdM', 'title': 'Shorts 2 - How to edit a Permission Tag'}, {'url': 'https://www.youtube.com/watch?v=gcZKN_JiDYk', 'title': 'Shorts 1 - Introduction to Interface'}, {'url': 'https://www.youtube.com/watch?v=hvWbD7Z2LrM', 'title': 'Shorts 2 - Update Project Configuration'}, {'url': 'https://www.youtube.com/watch?v=cmMoBIWyQt8', 'title': 'How To: Configure A Project in MissionOS'}]
2025-04-29 14:46:26,571 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-04-29 14:46:28,330 - httpx - INFO - HTTP Request: DELETE https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-04-29 14:46:28,994 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-04-29 14:49:08,888 - database - INFO - Processing 153 documents
2025-04-29 14:49:09,118 - database - INFO - Created 545 chunks/documents
2025-04-29 14:49:11,658 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points?wait=true "HTTP/1.1 200 OK"
2025-04-29 14:49:12,708 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points?wait=true "HTTP/1.1 200 OK"
2025-04-29 14:49:13,536 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points?wait=true "HTTP/1.1 200 OK"
2025-04-29 14:49:14,566 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points?wait=true "HTTP/1.1 200 OK"
2025-04-29 14:49:16,281 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points?wait=true "HTTP/1.1 200 OK"
2025-04-29 14:49:17,321 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points?wait=true "HTTP/1.1 200 OK"
2025-04-29 14:49:18,188 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points?wait=true "HTTP/1.1 200 OK"
2025-04-29 14:49:19,059 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points?wait=true "HTTP/1.1 200 OK"
2025-04-29 14:49:19,967 - httpx - INFO - HTTP Request: PUT https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points?wait=true "HTTP/1.1 200 OK"
2025-04-29 14:49:20,514 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-04-29 14:49:21,737 - ui - INFO - Rendering videos: [{'url': 'https://www.youtube.com/watch?v=POkNZPtGrQU', 'title': 'Shorts 1 - How to access Permission Tags'}, {'url': 'https://www.youtube.com/watch?v=H_cTgnXqkFQ', 'title': 'How To: Create Object Type Permissions'}, {'url': 'https://www.youtube.com/watch?v=Ffliy0elSdM', 'title': 'Shorts 2 - How to edit a Permission Tag'}, {'url': 'https://www.youtube.com/watch?v=gcZKN_JiDYk', 'title': 'Shorts 1 - Introduction to Interface'}, {'url': 'https://www.youtube.com/watch?v=hvWbD7Z2LrM', 'title': 'Shorts 2 - Update Project Configuration'}, {'url': 'https://www.youtube.com/watch?v=cmMoBIWyQt8', 'title': 'How To: Configure A Project in MissionOS'}]
2025-05-13 10:51:24,273 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 10:57:16,947 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 11:51:36,239 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 11:51:36,522 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 11:51:36,799 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 11:51:50,678 - langchain_google_genai.chat_models - WARNING - Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised NotFound: 404 models/gemini-pro is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods..
2025-05-13 11:52:37,567 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 11:53:00,499 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 11:53:39,708 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 11:53:53,993 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 11:53:56,873 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 11:53:57,164 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 11:53:57,442 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 11:54:27,047 - langchain_google_genai.chat_models - WARNING - Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised NotFound: 404 models/gemini-pro is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods..
2025-05-13 11:56:13,631 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 11:56:16,417 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 11:56:16,675 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 11:56:16,936 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 11:56:25,593 - langchain_google_genai.chat_models - WARNING - Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised NotFound: 404 models/chat-bison is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods..
2025-05-13 11:57:33,694 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 11:57:36,587 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 11:57:36,844 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 11:57:37,106 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 12:10:09,942 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 12:10:12,891 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 12:10:13,146 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 12:10:13,399 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 12:19:00,747 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 12:19:03,640 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 12:19:03,902 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 12:19:04,162 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 12:29:43,555 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 12:29:43,812 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 12:29:44,074 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 13:49:15,983 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 13:49:19,040 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 13:49:19,308 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 13:49:19,578 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 13:58:58,816 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 13:59:01,717 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 13:59:01,976 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 13:59:02,232 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 14:11:53,324 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 14:11:56,261 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 14:11:56,519 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 14:11:56,785 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 14:27:03,893 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 14:27:06,726 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 14:27:06,983 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 14:27:07,245 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 14:31:00,158 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 14:31:02,958 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 14:31:03,253 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 14:31:03,522 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 14:31:40,382 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 14:31:40,639 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 14:31:59,922 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 14:32:00,198 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 14:32:00,463 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 14:35:03,973 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 14:35:04,240 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 14:35:11,670 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 14:35:11,938 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 14:35:19,124 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 14:35:19,390 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 14:35:37,787 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 14:35:38,054 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 14:36:37,292 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 14:36:37,556 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 14:36:44,726 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 14:36:44,982 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 14:36:45,238 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 14:39:19,935 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 14:39:22,748 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 14:39:23,034 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 14:39:23,315 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 14:43:11,788 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 14:43:14,633 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 14:43:14,896 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 14:43:15,158 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 14:44:19,189 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 14:44:21,949 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 14:44:22,205 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 14:44:22,461 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 14:44:43,580 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 14:44:46,343 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 14:44:46,613 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 14:44:46,890 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 14:45:36,608 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 14:45:36,875 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 14:45:37,142 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 14:50:22,164 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 14:50:30,415 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 14:50:30,731 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 14:50:31,011 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 14:53:02,471 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 14:53:05,343 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 14:53:05,601 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 14:53:05,861 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 14:56:53,072 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 14:56:57,818 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 14:56:58,085 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 14:56:58,359 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 14:57:12,192 - httpx - INFO - HTTP Request: POST https://api.x.ai/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-13 14:57:13,766 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-13 14:57:32,873 - httpx - INFO - HTTP Request: POST https://api.x.ai/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-13 14:59:16,860 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 14:59:19,929 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 14:59:20,240 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 14:59:20,512 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 14:59:54,746 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-13 15:03:50,172 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 15:03:50,476 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 15:03:50,784 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 15:12:32,931 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 15:12:33,252 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 15:12:33,648 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 15:13:25,162 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 15:13:30,070 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 15:13:30,378 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 15:13:30,693 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 15:13:40,108 - httpx - INFO - HTTP Request: POST https://api.x.ai/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-13 15:13:56,992 - httpx - INFO - HTTP Request: POST https://api.x.ai/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-13 15:13:59,789 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-13 15:14:30,795 - httpx - INFO - HTTP Request: POST https://api.x.ai/v1/chat/completions "HTTP/1.1 200 OK"
2025-05-13 15:17:27,236 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 15:17:32,419 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 15:17:32,680 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 15:17:32,939 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 15:17:47,209 - httpx - INFO - HTTP Request: POST https://api.x.ai/v1/chat/completions "HTTP/1.1 404 Not Found"
2025-05-13 15:18:18,950 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 15:18:23,870 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 15:18:24,136 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 15:18:24,443 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 15:39:25,149 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 15:39:28,532 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 15:39:28,848 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 15:39:29,134 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 15:40:41,841 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 15:40:46,211 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 15:40:46,478 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 15:40:46,747 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 15:42:39,508 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 15:42:42,889 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 15:42:43,176 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 15:42:43,505 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 15:45:26,633 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 15:45:30,114 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 15:45:30,417 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 15:45:30,724 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 15:47:09,544 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 15:47:09,855 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 15:47:10,163 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 15:54:39,090 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 15:54:42,767 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 15:54:43,083 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 15:54:43,389 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 15:57:04,885 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 15:57:07,984 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 15:57:08,253 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 15:57:08,521 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 15:57:51,812 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 15:57:55,081 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 15:57:55,339 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 15:57:55,602 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 15:59:14,119 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 15:59:14,448 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 15:59:14,758 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 15:59:44,923 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 15:59:48,450 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 15:59:48,754 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 15:59:49,165 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 16:02:33,338 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 16:02:36,285 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 16:02:36,549 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 16:02:36,817 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 16:02:45,662 - langchain_google_genai.chat_models - WARNING - Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised NotFound: 404 models/gemini-pro is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods..
2025-05-13 16:03:54,914 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 16:03:55,186 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 16:03:55,459 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 16:04:04,149 - langchain_google_genai.chat_models - WARNING - Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised NotFound: 404 models/gemini-pro is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods..
2025-05-13 16:08:19,945 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 16:12:38,684 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 16:13:07,593 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 16:13:10,858 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 16:13:11,175 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 16:13:11,586 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 16:13:43,228 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-13 16:18:01,302 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 16:18:01,587 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 16:18:01,880 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 16:19:17,164 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-13 16:24:52,607 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 16:24:55,490 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 16:24:55,758 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 16:24:56,031 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 16:25:19,053 - langchain_google_genai.chat_models - WARNING - Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised NotFound: 404 models/gemini-2.5-pro-experimental is not found for API version v1beta, or is not supported for generateContent. Call ListModels to see the list of available models and their supported methods..
2025-05-13 16:26:42,921 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 16:26:45,994 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 16:26:46,301 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 16:26:46,607 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 16:28:57,637 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 16:29:00,962 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 16:29:01,238 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 16:29:01,574 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 16:29:27,690 - langchain_google_genai.chat_models - WARNING - Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-1.5-pro"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
}
violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-1.5-pro"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
}
violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_input_token_count"
  quota_id: "GenerateContentInputTokensPerModelPerMinute-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-1.5-pro"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 32
}
].
2025-05-13 16:31:57,615 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-13 16:32:00,386 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 16:32:00,655 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 16:32:00,926 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 16:32:25,650 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-13 17:01:20,521 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-13 17:01:20,792 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 17:01:21,064 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-13 18:38:13,194 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-23446' coro=<RefreshAheadCache._schedule_refresh.<locals>._refresh_task() done, defined at C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\instance.py:152> exception=TransportError(ConnectionError(MaxRetryError('HTTPSConnectionPool(host=\'oauth2.googleapis.com\', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB45CF430>: Failed to resolve \'oauth2.googleapis.com\' ([Errno 11001] getaddrinfo failed)"))')))>
Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\socket.py", line 967, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 488, in _make_request
    raise new_e
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connection.py", line 704, in connect
    self.sock = sock = self._new_conn()
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x0000016BB45CF430>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB45CF430>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\auth\transport\requests.py", line 186, in __call__
    response = self.session.request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB45CF430>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)"))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\instance.py", line 162, in _refresh_task
    refresh_data = await refresh_task
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\instance.py", line 117, in _perform_refresh
    connection_info = await self._client.get_connection_info(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\client.py", line 278, in get_connection_info
    self._credentials.refresh(requests.Request())
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\service_account.py", line 448, in refresh
    access_token, expiry, _ = _client.jwt_grant(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\_client.py", line 299, in jwt_grant
    response_data = _token_endpoint_request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\_client.py", line 259, in _token_endpoint_request
    response_status_ok, response_data, retryable_error = _token_endpoint_request_no_throw(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\_client.py", line 192, in _token_endpoint_request_no_throw
    response = request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\auth\transport\requests.py", line 192, in __call__
    raise new_exc from caught_exc
google.auth.exceptions.TransportError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB45CF430>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-13 18:38:13,215 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-23452' coro=<RefreshAheadCache._schedule_refresh.<locals>._refresh_task() done, defined at C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\instance.py:152> exception=TransportError(ConnectionError(MaxRetryError('HTTPSConnectionPool(host=\'oauth2.googleapis.com\', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB1FEEB00>: Failed to resolve \'oauth2.googleapis.com\' ([Errno 11001] getaddrinfo failed)"))')))>
Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\socket.py", line 967, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 488, in _make_request
    raise new_e
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connection.py", line 704, in connect
    self.sock = sock = self._new_conn()
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x0000016BB1FEEB00>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB1FEEB00>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\auth\transport\requests.py", line 186, in __call__
    response = self.session.request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB1FEEB00>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)"))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\instance.py", line 162, in _refresh_task
    refresh_data = await refresh_task
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\instance.py", line 117, in _perform_refresh
    connection_info = await self._client.get_connection_info(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\client.py", line 278, in get_connection_info
    self._credentials.refresh(requests.Request())
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\service_account.py", line 448, in refresh
    access_token, expiry, _ = _client.jwt_grant(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\_client.py", line 299, in jwt_grant
    response_data = _token_endpoint_request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\_client.py", line 259, in _token_endpoint_request
    response_status_ok, response_data, retryable_error = _token_endpoint_request_no_throw(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\_client.py", line 192, in _token_endpoint_request_no_throw
    response = request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\auth\transport\requests.py", line 192, in __call__
    raise new_exc from caught_exc
google.auth.exceptions.TransportError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB1FEEB00>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-13 18:38:13,250 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-23451' coro=<RefreshAheadCache._schedule_refresh.<locals>._refresh_task() done, defined at C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\instance.py:152> exception=TransportError(ConnectionError(MaxRetryError('HTTPSConnectionPool(host=\'oauth2.googleapis.com\', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB45CD6F0>: Failed to resolve \'oauth2.googleapis.com\' ([Errno 11001] getaddrinfo failed)"))')))>
Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\socket.py", line 967, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 488, in _make_request
    raise new_e
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connection.py", line 704, in connect
    self.sock = sock = self._new_conn()
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x0000016BB45CD6F0>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB45CD6F0>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\auth\transport\requests.py", line 186, in __call__
    response = self.session.request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB45CD6F0>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)"))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\instance.py", line 162, in _refresh_task
    refresh_data = await refresh_task
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\instance.py", line 117, in _perform_refresh
    connection_info = await self._client.get_connection_info(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\client.py", line 278, in get_connection_info
    self._credentials.refresh(requests.Request())
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\service_account.py", line 448, in refresh
    access_token, expiry, _ = _client.jwt_grant(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\_client.py", line 299, in jwt_grant
    response_data = _token_endpoint_request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\_client.py", line 259, in _token_endpoint_request
    response_status_ok, response_data, retryable_error = _token_endpoint_request_no_throw(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\_client.py", line 192, in _token_endpoint_request_no_throw
    response = request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\auth\transport\requests.py", line 192, in __call__
    raise new_exc from caught_exc
google.auth.exceptions.TransportError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB45CD6F0>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-13 18:38:13,282 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-23460' coro=<RefreshAheadCache._schedule_refresh.<locals>._refresh_task() done, defined at C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\instance.py:152> exception=TransportError(ConnectionError(MaxRetryError('HTTPSConnectionPool(host=\'oauth2.googleapis.com\', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB45CF460>: Failed to resolve \'oauth2.googleapis.com\' ([Errno 11001] getaddrinfo failed)"))')))>
Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\socket.py", line 967, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 488, in _make_request
    raise new_e
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connection.py", line 704, in connect
    self.sock = sock = self._new_conn()
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x0000016BB45CF460>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB45CF460>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\auth\transport\requests.py", line 186, in __call__
    response = self.session.request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB45CF460>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)"))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\instance.py", line 162, in _refresh_task
    refresh_data = await refresh_task
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\instance.py", line 117, in _perform_refresh
    connection_info = await self._client.get_connection_info(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\client.py", line 278, in get_connection_info
    self._credentials.refresh(requests.Request())
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\service_account.py", line 448, in refresh
    access_token, expiry, _ = _client.jwt_grant(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\_client.py", line 299, in jwt_grant
    response_data = _token_endpoint_request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\_client.py", line 259, in _token_endpoint_request
    response_status_ok, response_data, retryable_error = _token_endpoint_request_no_throw(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\_client.py", line 192, in _token_endpoint_request_no_throw
    response = request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\auth\transport\requests.py", line 192, in __call__
    raise new_exc from caught_exc
google.auth.exceptions.TransportError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB45CF460>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-13 18:38:13,329 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-23461' coro=<RefreshAheadCache._schedule_refresh.<locals>._refresh_task() done, defined at C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\instance.py:152> exception=TransportError(ConnectionError(MaxRetryError('HTTPSConnectionPool(host=\'oauth2.googleapis.com\', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB45CC2B0>: Failed to resolve \'oauth2.googleapis.com\' ([Errno 11001] getaddrinfo failed)"))')))>
Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\socket.py", line 967, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 488, in _make_request
    raise new_e
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connection.py", line 704, in connect
    self.sock = sock = self._new_conn()
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x0000016BB45CC2B0>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB45CC2B0>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\auth\transport\requests.py", line 186, in __call__
    response = self.session.request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB45CC2B0>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)"))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\instance.py", line 162, in _refresh_task
    refresh_data = await refresh_task
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\instance.py", line 117, in _perform_refresh
    connection_info = await self._client.get_connection_info(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\client.py", line 278, in get_connection_info
    self._credentials.refresh(requests.Request())
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\service_account.py", line 448, in refresh
    access_token, expiry, _ = _client.jwt_grant(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\_client.py", line 299, in jwt_grant
    response_data = _token_endpoint_request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\_client.py", line 259, in _token_endpoint_request
    response_status_ok, response_data, retryable_error = _token_endpoint_request_no_throw(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\_client.py", line 192, in _token_endpoint_request_no_throw
    response = request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\auth\transport\requests.py", line 192, in __call__
    raise new_exc from caught_exc
google.auth.exceptions.TransportError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB45CC2B0>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-13 18:38:13,369 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-23463' coro=<RefreshAheadCache._schedule_refresh.<locals>._refresh_task() done, defined at C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\instance.py:152> exception=TransportError(ConnectionError(MaxRetryError('HTTPSConnectionPool(host=\'oauth2.googleapis.com\', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB9E43C40>: Failed to resolve \'oauth2.googleapis.com\' ([Errno 11001] getaddrinfo failed)"))')))>
Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\socket.py", line 967, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 488, in _make_request
    raise new_e
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connection.py", line 704, in connect
    self.sock = sock = self._new_conn()
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x0000016BB9E43C40>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB9E43C40>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\auth\transport\requests.py", line 186, in __call__
    response = self.session.request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB9E43C40>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)"))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\instance.py", line 162, in _refresh_task
    refresh_data = await refresh_task
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\instance.py", line 117, in _perform_refresh
    connection_info = await self._client.get_connection_info(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\client.py", line 278, in get_connection_info
    self._credentials.refresh(requests.Request())
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\service_account.py", line 448, in refresh
    access_token, expiry, _ = _client.jwt_grant(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\_client.py", line 299, in jwt_grant
    response_data = _token_endpoint_request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\_client.py", line 259, in _token_endpoint_request
    response_status_ok, response_data, retryable_error = _token_endpoint_request_no_throw(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\_client.py", line 192, in _token_endpoint_request_no_throw
    response = request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\auth\transport\requests.py", line 192, in __call__
    raise new_exc from caught_exc
google.auth.exceptions.TransportError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB9E43C40>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-14 04:32:13,602 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-23465' coro=<RefreshAheadCache._schedule_refresh.<locals>._refresh_task() done, defined at C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\instance.py:152> exception=TransportError(ConnectionError(MaxRetryError('HTTPSConnectionPool(host=\'oauth2.googleapis.com\', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB45CD300>: Failed to resolve \'oauth2.googleapis.com\' ([Errno 11001] getaddrinfo failed)"))')))>
Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\socket.py", line 967, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 488, in _make_request
    raise new_e
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connection.py", line 704, in connect
    self.sock = sock = self._new_conn()
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x0000016BB45CD300>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB45CD300>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\auth\transport\requests.py", line 186, in __call__
    response = self.session.request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB45CD300>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)"))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\instance.py", line 162, in _refresh_task
    refresh_data = await refresh_task
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\instance.py", line 117, in _perform_refresh
    connection_info = await self._client.get_connection_info(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\client.py", line 278, in get_connection_info
    self._credentials.refresh(requests.Request())
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\service_account.py", line 448, in refresh
    access_token, expiry, _ = _client.jwt_grant(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\_client.py", line 299, in jwt_grant
    response_data = _token_endpoint_request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\_client.py", line 259, in _token_endpoint_request
    response_status_ok, response_data, retryable_error = _token_endpoint_request_no_throw(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\_client.py", line 192, in _token_endpoint_request_no_throw
    response = request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\auth\transport\requests.py", line 192, in __call__
    raise new_exc from caught_exc
google.auth.exceptions.TransportError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB45CD300>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-14 04:32:13,638 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-23469' coro=<RefreshAheadCache._schedule_refresh.<locals>._refresh_task() done, defined at C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\instance.py:152> exception=TransportError(ConnectionError(MaxRetryError('HTTPSConnectionPool(host=\'oauth2.googleapis.com\', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB9E43AC0>: Failed to resolve \'oauth2.googleapis.com\' ([Errno 11001] getaddrinfo failed)"))')))>
Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\socket.py", line 967, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 488, in _make_request
    raise new_e
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connection.py", line 704, in connect
    self.sock = sock = self._new_conn()
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x0000016BB9E43AC0>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB9E43AC0>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\auth\transport\requests.py", line 186, in __call__
    response = self.session.request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB9E43AC0>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)"))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\instance.py", line 162, in _refresh_task
    refresh_data = await refresh_task
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\instance.py", line 117, in _perform_refresh
    connection_info = await self._client.get_connection_info(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\client.py", line 278, in get_connection_info
    self._credentials.refresh(requests.Request())
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\service_account.py", line 448, in refresh
    access_token, expiry, _ = _client.jwt_grant(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\_client.py", line 299, in jwt_grant
    response_data = _token_endpoint_request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\_client.py", line 259, in _token_endpoint_request
    response_status_ok, response_data, retryable_error = _token_endpoint_request_no_throw(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\_client.py", line 192, in _token_endpoint_request_no_throw
    response = request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\auth\transport\requests.py", line 192, in __call__
    raise new_exc from caught_exc
google.auth.exceptions.TransportError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB9E43AC0>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-14 04:32:13,620 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-23466' coro=<RefreshAheadCache._schedule_refresh.<locals>._refresh_task() done, defined at C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\instance.py:152> exception=TransportError(ConnectionError(MaxRetryError('HTTPSConnectionPool(host=\'oauth2.googleapis.com\', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB45CDC30>: Failed to resolve \'oauth2.googleapis.com\' ([Errno 11001] getaddrinfo failed)"))')))>
Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\socket.py", line 967, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 488, in _make_request
    raise new_e
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connection.py", line 704, in connect
    self.sock = sock = self._new_conn()
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x0000016BB45CDC30>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB45CDC30>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\auth\transport\requests.py", line 186, in __call__
    response = self.session.request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB45CDC30>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)"))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\instance.py", line 162, in _refresh_task
    refresh_data = await refresh_task
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\instance.py", line 117, in _perform_refresh
    connection_info = await self._client.get_connection_info(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\client.py", line 278, in get_connection_info
    self._credentials.refresh(requests.Request())
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\service_account.py", line 448, in refresh
    access_token, expiry, _ = _client.jwt_grant(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\_client.py", line 299, in jwt_grant
    response_data = _token_endpoint_request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\_client.py", line 259, in _token_endpoint_request
    response_status_ok, response_data, retryable_error = _token_endpoint_request_no_throw(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\_client.py", line 192, in _token_endpoint_request_no_throw
    response = request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\auth\transport\requests.py", line 192, in __call__
    raise new_exc from caught_exc
google.auth.exceptions.TransportError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB45CDC30>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-14 04:32:13,661 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-23486' coro=<RefreshAheadCache._schedule_refresh.<locals>._refresh_task() done, defined at C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\instance.py:152> exception=TransportError(ConnectionError(MaxRetryError('HTTPSConnectionPool(host=\'oauth2.googleapis.com\', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016B85D0C160>: Failed to resolve \'oauth2.googleapis.com\' ([Errno 11001] getaddrinfo failed)"))')))>
Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\socket.py", line 967, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 488, in _make_request
    raise new_e
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connection.py", line 704, in connect
    self.sock = sock = self._new_conn()
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x0000016B85D0C160>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016B85D0C160>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\auth\transport\requests.py", line 186, in __call__
    response = self.session.request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016B85D0C160>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)"))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\instance.py", line 162, in _refresh_task
    refresh_data = await refresh_task
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\instance.py", line 117, in _perform_refresh
    connection_info = await self._client.get_connection_info(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\client.py", line 278, in get_connection_info
    self._credentials.refresh(requests.Request())
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\service_account.py", line 448, in refresh
    access_token, expiry, _ = _client.jwt_grant(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\_client.py", line 299, in jwt_grant
    response_data = _token_endpoint_request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\_client.py", line 259, in _token_endpoint_request
    response_status_ok, response_data, retryable_error = _token_endpoint_request_no_throw(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\_client.py", line 192, in _token_endpoint_request_no_throw
    response = request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\auth\transport\requests.py", line 192, in __call__
    raise new_exc from caught_exc
google.auth.exceptions.TransportError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016B85D0C160>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-14 04:32:13,677 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-23488' coro=<RefreshAheadCache._schedule_refresh.<locals>._refresh_task() done, defined at C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\instance.py:152> exception=TransportError(ConnectionError(MaxRetryError('HTTPSConnectionPool(host=\'oauth2.googleapis.com\', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB4533C40>: Failed to resolve \'oauth2.googleapis.com\' ([Errno 11001] getaddrinfo failed)"))')))>
Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\socket.py", line 967, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 488, in _make_request
    raise new_e
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connection.py", line 704, in connect
    self.sock = sock = self._new_conn()
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x0000016BB4533C40>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB4533C40>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\auth\transport\requests.py", line 186, in __call__
    response = self.session.request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB4533C40>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)"))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\instance.py", line 162, in _refresh_task
    refresh_data = await refresh_task
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\instance.py", line 117, in _perform_refresh
    connection_info = await self._client.get_connection_info(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\client.py", line 278, in get_connection_info
    self._credentials.refresh(requests.Request())
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\service_account.py", line 448, in refresh
    access_token, expiry, _ = _client.jwt_grant(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\_client.py", line 299, in jwt_grant
    response_data = _token_endpoint_request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\_client.py", line 259, in _token_endpoint_request
    response_status_ok, response_data, retryable_error = _token_endpoint_request_no_throw(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\_client.py", line 192, in _token_endpoint_request_no_throw
    response = request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\auth\transport\requests.py", line 192, in __call__
    raise new_exc from caught_exc
google.auth.exceptions.TransportError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB4533C40>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-14 04:32:13,799 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-23487' coro=<RefreshAheadCache._schedule_refresh.<locals>._refresh_task() done, defined at C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\instance.py:152> exception=TransportError(ConnectionError(MaxRetryError('HTTPSConnectionPool(host=\'oauth2.googleapis.com\', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB45322C0>: Failed to resolve \'oauth2.googleapis.com\' ([Errno 11001] getaddrinfo failed)"))')))>
Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\socket.py", line 967, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 488, in _make_request
    raise new_e
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connection.py", line 704, in connect
    self.sock = sock = self._new_conn()
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connection.py", line 205, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x0000016BB45322C0>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\connectionpool.py", line 841, in urlopen
    retries = retries.increment(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB45322C0>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\auth\transport\requests.py", line 186, in __call__
    response = self.session.request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB45322C0>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)"))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\instance.py", line 162, in _refresh_task
    refresh_data = await refresh_task
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\instance.py", line 117, in _perform_refresh
    connection_info = await self._client.get_connection_info(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\cloud\sql\connector\client.py", line 278, in get_connection_info
    self._credentials.refresh(requests.Request())
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\service_account.py", line 448, in refresh
    access_token, expiry, _ = _client.jwt_grant(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\_client.py", line 299, in jwt_grant
    response_data = _token_endpoint_request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\_client.py", line 259, in _token_endpoint_request
    response_status_ok, response_data, retryable_error = _token_endpoint_request_no_throw(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\oauth2\_client.py", line 192, in _token_endpoint_request_no_throw
    response = request(
  File "C:\Users\maxwe\anaconda3\envs\rag-eval\lib\site-packages\google\auth\transport\requests.py", line 192, in __call__
    raise new_exc from caught_exc
google.auth.exceptions.TransportError: HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016BB45322C0>: Failed to resolve 'oauth2.googleapis.com' ([Errno 11001] getaddrinfo failed)"))
2025-05-14 11:57:27,558 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-14 11:57:42,385 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 11:57:42,657 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 11:57:42,948 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 12:40:54,842 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-14 12:40:57,735 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 12:40:58,013 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 12:40:58,288 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 12:41:13,591 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 12:51:00,868 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-14 12:51:03,654 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 12:51:03,925 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 12:51:04,200 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 12:51:14,404 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 12:51:46,518 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 12:51:46,793 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 12:51:47,056 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 12:52:00,609 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 12:58:07,198 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-14 12:58:10,203 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 12:58:11,539 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 12:58:11,865 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 13:01:11,858 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-14 13:01:14,663 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 13:01:14,926 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 13:01:15,187 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 14:05:16,136 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 14:05:16,420 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 14:05:16,701 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 14:07:55,625 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-14 14:07:58,329 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 14:07:58,587 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 14:07:58,840 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 14:08:46,068 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-14 14:08:49,846 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 14:08:50,152 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 14:08:50,462 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 14:09:06,575 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 14:16:33,855 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-14 14:16:36,753 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 14:16:37,022 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 14:16:37,297 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 14:16:58,348 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 14:22:05,805 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 14:22:06,072 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 14:22:06,342 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 14:22:23,271 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 14:22:54,559 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 14:23:27,166 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 14:23:57,079 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 14:24:43,121 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 14:25:33,860 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 14:25:34,126 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 14:25:34,399 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 14:26:03,233 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 14:26:50,341 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 14:29:27,914 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 14:33:36,264 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 14:33:36,518 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 14:33:36,775 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 14:33:58,607 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 14:48:21,950 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 14:59:07,925 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 14:59:08,183 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 14:59:08,441 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 14:59:29,851 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 15:01:35,863 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 15:02:07,683 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 15:02:07,946 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 15:02:08,207 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 15:02:21,828 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 15:03:05,385 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 15:03:37,959 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 15:03:38,229 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 15:03:38,501 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 15:03:57,445 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 15:05:06,787 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 15:21:32,078 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-14 15:21:34,950 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 15:21:35,216 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 15:21:35,483 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 15:23:29,438 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-14 15:23:32,232 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 15:23:32,504 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 15:23:32,777 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 15:23:45,184 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 15:25:52,318 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-14 15:25:55,230 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 15:25:55,507 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 15:25:55,784 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 15:26:08,647 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 15:27:05,858 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-14 15:27:08,730 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 15:27:08,987 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 15:27:09,244 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 15:27:25,254 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 15:27:46,383 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 15:29:17,504 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 15:29:17,770 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 15:29:18,040 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 15:29:46,412 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 15:31:17,200 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 15:46:20,944 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-14 15:46:23,783 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 15:46:24,041 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 15:46:24,298 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 15:47:25,239 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 15:52:05,720 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-14 15:52:08,747 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 15:52:09,011 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 15:52:09,291 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 15:53:02,076 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-14 15:53:05,192 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 15:53:05,461 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 15:53:05,731 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 15:53:45,377 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-14 15:53:48,304 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 15:53:48,592 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 15:53:48,874 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 15:54:18,155 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 15:54:18,450 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 15:54:18,733 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 15:54:59,889 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 15:55:00,183 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 15:55:00,452 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 15:57:10,918 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-14 15:57:17,776 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 15:57:18,046 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 15:57:18,322 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 15:57:42,009 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 15:59:05,768 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-14 15:59:11,853 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 15:59:12,111 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 15:59:12,376 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:01:29,511 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 16:01:29,765 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:01:30,018 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:01:59,101 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 16:01:59,366 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:01:59,636 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:02:43,856 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-14 16:02:49,782 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 16:02:50,041 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:02:50,298 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:04:03,621 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-14 16:04:06,391 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 16:04:06,675 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:04:06,960 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:05:45,088 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-14 16:05:47,828 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 16:05:48,091 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:05:48,357 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:06:35,209 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-14 16:06:39,189 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 16:06:39,456 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:06:39,726 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:07:15,842 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 16:07:16,100 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:07:16,357 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:08:16,675 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-14 16:08:19,487 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 16:08:19,750 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:08:20,009 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:09:41,594 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-14 16:09:47,428 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 16:09:47,683 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:09:47,941 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:10:06,662 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 16:15:27,511 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 16:15:27,770 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:15:28,029 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:16:02,421 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 16:16:24,639 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 16:16:53,970 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 16:22:20,104 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-14 16:22:22,971 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 16:22:23,239 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:22:23,505 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:22:30,638 - langchain_google_genai.chat_models - WARNING - Retrying langchain_google_genai.chat_models._chat_with_retry.<locals>._chat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_input_token_count"
  quota_id: "GenerateContentInputTokensPerModelPerMinute-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-1.5-pro"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
}
violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-1.5-pro"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
}
violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerDayPerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-1.5-pro"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 30
}
].
2025-05-14 16:22:52,045 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-14 16:22:54,929 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 16:22:55,193 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:22:55,455 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:23:29,247 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 16:39:09,923 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-14 16:39:12,773 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 16:39:13,029 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:39:13,286 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:39:26,438 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 16:40:01,539 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 16:40:32,662 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 16:40:48,556 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 16:40:48,819 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:40:49,087 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:41:09,914 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 16:42:48,983 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-14 16:42:51,734 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 16:42:52,005 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:42:52,276 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:43:36,645 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 16:44:24,462 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333 "HTTP/1.1 200 OK"
2025-05-14 16:44:27,396 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 16:44:27,660 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:44:27,926 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:44:38,459 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 16:45:01,294 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 16:45:32,574 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 16:49:01,493 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 16:49:01,757 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:49:02,035 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:49:26,665 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 16:49:26,922 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:49:27,193 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:49:48,177 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
2025-05-14 16:50:17,944 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections "HTTP/1.1 200 OK"
2025-05-14 16:50:18,204 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:50:18,467 - httpx - INFO - HTTP Request: GET https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text "HTTP/1.1 200 OK"
2025-05-14 16:50:42,683 - httpx - INFO - HTTP Request: POST https://73e9e4e2-a9ce-4aa8-ae1d-fac6e5660e33.us-west-2-0.aws.cloud.qdrant.io:6333/collections/manual-text/points/query "HTTP/1.1 200 OK"
